Additive Widgets: additive Class Reference
additive Class Reference
Main window class
#include <additive.h>
Classes
class vtkMyShader
Public Slots
void slot_listitementered (QListWidgetItem *item)
Slot called when mouse is hovering over list item
void slot_listitemclicked (int i)
Slot called when list item clicked (i is the index of the clicked item)
void slot_buttonclicked ()
Slot called when the Show Edge button clicked
void slot_newwindow ()
Slot called when File->New Window menu item clicked
void slot_timeout ()
Slot called as frequently as possible (refreshes qvtkWidget)
void slot_open ()
Slot called when File->Open clicked
void slot_exit ()
Slot called when File->Exit clicked
void slot_fullScreen ()
Slot called when fullscreen menu item clicked
void slot_valueChanged (int i)
Slot called when opacity slider value changed
void slot_afterShowWindow ()
Slot called after window is loaded and shown
Public Member Functions
additive (QWidget *parent=0, Qt::WFlags flags=0)
The constructor (Fires a timer that starts slot_afterShowWindow which has all initialization code)
~additive ()
Finalizes an instance of the additive class.
virtual void resizeEvent (QResizeEvent *) override
Event called when window resized (resizes qvtkwidget)
virtual void mouseMoveEvent (QMouseEvent *) override
Event called when mouse moves over window
void readFile (char *filename)
Reads an .obj file and loads into meshes vector
void print_statusbar (std::string text)
Changes label in status bar to a new message
void updateDisplay ()
void setDiffuseAndOpacity ()
Sets the diffuse and opacity properties of all objects to the ones set in meshes vector
void updateMouseShader ()
void updateMat ()
void updateMat (int z)
Public Attributes
double mouse [3]
float mouseSize
float brushDivide
int peerInside
int toon
QVTKWidget * qv
vtkSmartPointer< vtkRenderer > renderer
VTK renderer
std::vector< CustomMesh > meshes
Vector of CustomMesh objects
int selectedIndex
Currently selected mesh index
vtkSmartPointer< vtkActor > mainCursor
Detailed Description
Main window class
Definition at line 63 of file additive.h.
Constructor & Destructor Documentation
additive::additive (QWidget * parent = 0, Qt::WFlags flags = 0)
The constructor (Fires a timer that starts slot_afterShowWindow which has all initialization code)
Definition at line 79 of file additive.cpp.
References slot_afterShowWindow().
additive::~additive ()
Finalizes an instance of the additive class.
Definition at line 89 of file additive.cpp.
Member Function Documentation
void additive::mouseMoveEvent (QMouseEvent *) override virtual
Event called when mouse moves over window
Event object (Qt-based)
Definition at line 222 of file additive.cpp.
References meshes.
void additive::print_statusbar (std::string text) inline
Changes label in status bar to a new message
Parameters
text The message.
Definition at line 335 of file additive.h.
Referenced by slot_buttonclicked(), slot_newwindow(), and slot_open().
void additive::readFile (char * filename)
Reads an .obj file and loads into meshes vector
Parameters
filename filename.
Definition at line 238 of file additive.cpp.
References Utility::end_clock(), meshes, renderer, selectedIndex, and Utility::start_clock().
Referenced by slot_afterShowWindow(), and slot_open().
void additive::resizeEvent (QResizeEvent * event) override virtual
Event called when window resized (resizes qvtkwidget)
Parameters
event Event object (Qt-based)
Definition at line 203 of file additive.cpp.
void additive::setDiffuseAndOpacity () inline
Sets the diffuse and opacity properties of all objects to the ones set in meshes vector
Definition at line 357 of file additive.h.
References meshes.
Referenced by slot_listitemclicked(), and slot_valueChanged().
void additive::slot_afterShowWindow () slot
Slot called after window is loaded and shown
Slot called after the window is fully loaded (contains all initialization code)
Definition at line 97 of file additive.cpp.
References readFile(), renderer, slot_buttonclicked(), slot_exit(), slot_listitemclicked(), slot_listitementered(), slot_newwindow(), slot_open(), slot_timeout(), and slot_valueChanged().
Referenced by additive().
void additive::slot_buttonclicked () inline slot
Slot called when the Show Edge button clicked
Definition at line 161 of file additive.h.
References meshes, print_statusbar(), and selectedIndex.
Referenced by slot_afterShowWindow().
void additive::slot_exit () inline slot
Slot called when File->Exit clicked
Definition at line 247 of file additive.h.
Referenced by slot_afterShowWindow().
void additive::slot_fullScreen () inline slot
Slot called when fullscreen menu item clicked
Definition at line 259 of file additive.h.
void additive::slot_listitemclicked (int i) inline slot
Slot called when list item clicked (i is the index of the clicked item)
Parameters
i Clicked item index
Definition at line 136 of file additive.h.
References meshes, selectedIndex, and setDiffuseAndOpacity().
Referenced by slot_afterShowWindow().
void additive::slot_listitementered (QListWidgetItem * item) inline slot
Slot called when mouse is hovering over list item
Definition at line 121 of file additive.h.
Referenced by slot_afterShowWindow().
void additive::slot_newwindow () inline slot
Slot called when File->New Window menu item clicked
Definition at line 189 of file additive.h.
References print_statusbar().
Referenced by slot_afterShowWindow().
void additive::slot_open () inline slot
Slot called when File->Open clicked
Definition at line 218 of file additive.h.
References print_statusbar(), readFile(), and renderer.
Referenced by slot_afterShowWindow().
void additive::slot_timeout () inline slot
Slot called as frequently as possible (refreshes qvtkWidget)
Definition at line 198 of file additive.h.
Referenced by slot_afterShowWindow().
void additive::slot_valueChanged (int i) inline slot
Slot called when opacity slider value changed
Parameters
i new opacity value
Definition at line 270 of file additive.h.
References meshes, selectedIndex, and setDiffuseAndOpacity().
Referenced by slot_afterShowWindow().
Member Data Documentation
std::vector<CustomMesh> additive::meshes
Vector of CustomMesh objects
Definition at line 88 of file additive.h.
Referenced by mouseMoveEvent(), MouseInteractorStylePP::OnMouseMove(), readFile(), setDiffuseAndOpacity(), slot_buttonclicked(), slot_listitemclicked(), and slot_valueChanged().
vtkSmartPointer<vtkRenderer> additive::renderer
VTK renderer
Definition at line 85 of file additive.h.
Referenced by MouseInteractorStylePP::OnKeyPress(), readFile(), slot_afterShowWindow(), and slot_open().
int additive::selectedIndex
Currently selected mesh index
Definition at line 91 of file additive.h.
Referenced by MouseInteractorStylePP::OnMouseMove(), readFile(), slot_buttonclicked(), slot_listitemclicked(), and slot_valueChanged().
The documentation for this class was generated from the following files:
additive.h
additive.cpp