var files =
[
    [ "GeneratedFiles", "dir_8838c8859190145fd5c0dbb93d82e03f.html", "dir_8838c8859190145fd5c0dbb93d82e03f" ],
    [ "additive.cpp", "additive_8cpp_source.html", null ],
    [ "additive.h", "additive_8h_source.html", null ],
    [ "CheckForMemoryLeaks.h", "_check_for_memory_leaks_8h_source.html", null ],
    [ "main.cpp", "main_8cpp_source.html", null ],
    [ "MyInteractor.h", "_my_interactor_8h_source.html", null ],
    [ "myOBJReader.cpp", "my_o_b_j_reader_8cpp_source.html", null ],
    [ "myOBJReader.h", "my_o_b_j_reader_8h_source.html", null ],
    [ "myOBJReader_Exp.cpp", "my_o_b_j_reader___exp_8cpp_source.html", null ],
    [ "myOBJReader_Exp.h", "my_o_b_j_reader___exp_8h_source.html", null ],
    [ "MySuperquadric.cpp", "_my_superquadric_8cpp_source.html", null ],
    [ "MySuperquadric.h", "_my_superquadric_8h_source.html", null ],
    [ "MySuperquadricSource.cpp", "_my_superquadric_source_8cpp_source.html", null ],
    [ "MySuperquadricSource.h", "_my_superquadric_source_8h_source.html", null ],
    [ "obj_parser.cpp", "obj__parser_8cpp_source.html", null ],
    [ "obj_parser.h", "obj__parser_8h_source.html", null ],
    [ "resource.h", "resource_8h_source.html", null ],
    [ "stdafx.cpp", "stdafx_8cpp_source.html", null ],
    [ "stdafx.h", "stdafx_8h_source.html", null ],
    [ "StdDefines.h", "_std_defines_8h_source.html", null ],
    [ "Superquadrics.h", "_superquadrics_8h_source.html", null ],
    [ "Utility.cpp", "_utility_8cpp_source.html", null ],
    [ "Utility.h", "_utility_8h_source.html", null ],
    [ "Vectors.h", "_vectors_8h.html", "_vectors_8h" ],
    [ "vtkMyProcessingPass.cpp", "vtk_my_processing_pass_8cpp_source.html", null ],
    [ "vtkMyProcessingPass.h", "vtk_my_processing_pass_8h_source.html", null ],
    [ "vtkMyShaderPass.cpp", "vtk_my_shader_pass_8cpp_source.html", null ],
    [ "vtkMyShaderPass.h", "vtk_my_shader_pass_8h_source.html", null ]
];